mybatis-plus:
    global-config:
        enable-sql-runner: true
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/logistics
        username: root
        password: 2003219
        driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
    api-docs:
        enabled: true
    swagger-ui: