package org.graduation.logistics.dao;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.graduation.logistics.entity.bo.WaybillBo;
import org.graduation.logistics.entity.pojo.Waybill;

import java.sql.Timestamp;
import java.util.List;

public interface WaybillDao extends BaseMapper<Waybill> {
    @Select("<script>"
            + "SELECT "
            + "w.waybill_id AS waybillId, "
            + "w.user_id AS userId, "
            + "w.sender_address_id AS senderAddressId, "
            + "w.receiver_address_id AS receiverAddressId, "
            + "w.package_id AS packageId, "
            + "w.create_time AS createTime, "
            + "w.channel_id AS channelId, "
            + "w.status, "
            + "w.store_id AS storeId, "
            + "w.logistics_type AS logisticsType, "
            + "w.created_time AS createdTime, "
            + "w.paid_time AS paidTime, "
            + "w.sent_to_hub_time AS sentToHubTime, "
            + "w.shipped_from_hub_time AS shippedFromHubTime, "
            + "w.arrived_customs_time AS arrivedCustomsTime, "
            + "w.delivery_time AS deliveryTime, "
            + "w.delivery_confirmation_time AS deliveryConfirmationTime, "
            + "a1.address_id AS senderAddress.addressId, "
            + "CASE WHEN #{language} = 1 THEN a1.chinese_name ELSE a1.english_name END AS senderAddress.name, "
            + "a2.address_id AS receiverAddress.addressId, "
            + "CASE WHEN #{language} = 1 THEN a2.chinese_name ELSE a2.english_name END AS receiverAddress.name, "
            + "p.package_id AS packageBo.packageId, "
            + "c.channel_id AS channel.channelId, "
            + "CASE WHEN #{language} = 1 THEN c.chinese_name ELSE c.english_name END AS channel.name, "
            + "st.store_id AS storeId, "
            + "CASE WHEN #{language} = 1 THEN st.chinese_name ELSE st.english_name END AS storeName "
            + "FROM waybill w "
            + "LEFT JOIN address a1 ON w.sender_address_id = a1.address_id "
            + "LEFT JOIN address a2 ON w.receiver_address_id = a2.address_id "
            + "LEFT JOIN package p ON w.package_id = p.package_id "
            + "LEFT JOIN channel c ON w.channel_id = c.channel_id "
            + "LEFT JOIN store st ON w.store_id = st.store_id "
            + "WHERE w.store_id = #{storeId} "
            + "</script>")
    List<WaybillBo> selectWaybillBosByStoreId(@Param("storeId") Integer storeId, @Param("language") Integer language);
    @Select("<script>"
            + "SELECT "
            + "w.waybill_id AS waybillId, "
            + "w.user_id AS userId, "
            + "w.sender_address_id AS senderAddressId, "
            + "w.receiver_address_id AS receiverAddressId, "
            + "w.package_id AS packageId, "
            + "w.create_time AS createTime, "
            + "w.channel_id AS channelId, "
            + "w.status, "
            + "w.store_id AS storeId, "
            + "w.logistics_type AS logisticsType, "
            + "w.created_time AS createdTime, "
            + "w.paid_time AS paidTime, "
            + "w.sent_to_hub_time AS sentToHubTime, "
            + "w.shipped_from_hub_time AS shippedFromHubTime, "
            + "w.arrived_customs_time AS arrivedCustomsTime, "
            + "w.delivery_time AS deliveryTime, "
            + "w.delivery_confirmation_time AS deliveryConfirmationTime, "
            + "a1.address_id AS senderAddress.addressId, "
            + "CASE WHEN #{language} = 1 THEN a1.chinese_name ELSE a1.english_name END AS senderAddress.name, "
            + "a2.address_id AS receiverAddress.addressId, "
            + "CASE WHEN #{language} = 1 THEN a2.chinese_name ELSE a2.english_name END AS receiverAddress.name, "
            + "p.package_id AS packageBo.packageId, "
            + "c.channel_id AS channel.channelId, "
            + "CASE WHEN #{language} = 1 THEN c.chinese_name ELSE c.english_name END AS channel.name, "
            + "st.store_id AS storeId, "
            + "CASE WHEN #{language} = 1 THEN st.chinese_name ELSE st.english_name END AS storeName "
            + "FROM waybill w "
            + "LEFT JOIN address a1 ON w.sender_address_id = a1.address_id "
            + "LEFT JOIN address a2 ON w.receiver_address_id = a2.address_id "
            + "LEFT JOIN package p ON w.package_id = p.package_id "
            + "LEFT JOIN channel c ON w.channel_id = c.channel_id "
            + "LEFT JOIN store st ON w.store_id = st.store_id "
            + "WHERE w.waybill_id = #{waybillId} "
            + "</script>")
    WaybillBo selectWaybillBoByWaybillId(@Param("waybillId") Integer waybillId, @Param("language") Integer language);
    @Select("<script>"
            + "SELECT "
            + "w.waybill_id AS waybillId, "
            + "w.user_id AS userId, "
            + "w.sender_address_id AS senderAddressId, "
            + "w.receiver_address_id AS receiverAddressId, "
            + "w.package_id AS packageId, "
            + "w.create_time AS createTime, "
            + "w.channel_id AS channelId, "
            + "w.status, "
            + "w.store_id AS storeId, "
            + "w.logistics_type AS logisticsType, "
            + "w.created_time AS createdTime, "
            + "w.paid_time AS paidTime, "
            + "w.sent_to_hub_time AS sentToHubTime, "
            + "w.shipped_from_hub_time AS shippedFromHubTime, "
            + "w.arrived_customs_time AS arrivedCustomsTime, "
            + "w.delivery_time AS deliveryTime, "
            + "w.delivery_confirmation_time AS deliveryConfirmationTime, "
            + "a1.address_id AS senderAddress.addressId, "
            + "CASE WHEN #{language} = 1 THEN a1.chinese_name ELSE a1.english_name END AS senderAddress.name, "
            + "a2.address_id AS receiverAddress.addressId, "
            + "CASE WHEN #{language} = 1 THEN a2.chinese_name ELSE a2.english_name END AS receiverAddress.name, "
            + "p.package_id AS packageBo.packageId, "
            + "c.channel_id AS channel.channelId, "
            + "CASE WHEN #{language} = 1 THEN c.chinese_name ELSE c.english_name END AS channel.name "
            + "FROM waybill w "
            + "LEFT JOIN address a1 ON w.sender_address_id = a1.address_id "
            + "LEFT JOIN address a2 ON w.receiver_address_id = a2.address_id "
            + "LEFT JOIN package p ON w.package_id = p.package_id "
            + "LEFT JOIN channel c ON w.channel_id = c.channel_id "
            + "WHERE w.create_time BETWEEN #{startTime} AND #{endTime} "
            + "And w.storeId = #{storeId}"
            + "</script>")
    List<WaybillBo> selectWaybillBosByCreateTimeAndStoreId(@Param("storeId") Integer storeId,
                                                           @Param("startTime") Timestamp startTime,
                                                            @Param("endTime") Timestamp endTime,
                                                            @Param("language") Integer language);
    @Select("<script>"
            + "SELECT "
            + "w.waybill_id AS waybillId, "
            + "w.user_id AS userId, "
            + "w.sender_address_id AS senderAddressId, "
            + "w.receiver_address_id AS receiverAddressId, "
            + "w.package_id AS packageId, "
            + "w.create_time AS createTime, "
            + "w.channel_id AS channelId, "
            + "w.status, "
            + "w.store_id AS storeId, "
            + "w.logistics_type AS logisticsType, "
            + "w.created_time AS createdTime, "
            + "w.paid_time AS paidTime, "
            + "w.sent_to_hub_time AS sentToHubTime, "
            + "w.shipped_from_hub_time AS shippedFromHubTime, "
            + "w.arrived_customs_time AS arrivedCustomsTime, "
            + "w.delivery_time AS deliveryTime, "
            + "w.delivery_confirmation_time AS deliveryConfirmationTime, "
            + "a1.address_id AS senderAddress.addressId, "
            + "CASE WHEN #{language} = 1 THEN a1.chinese_name ELSE a1.english_name END AS senderAddress.name, "
            + "a2.address_id AS receiverAddress.addressId, "
            + "CASE WHEN #{language} = 1 THEN a2.chinese_name ELSE a2.english_name END AS receiverAddress.name, "
            + "p.package_id AS packageBo.packageId, "
            + "c.channel_id AS channel.channelId, "
            + "CASE WHEN #{language} = 1 THEN c.chinese_name ELSE c.english_name END AS channel.name "
            + "FROM waybill w "
            + "LEFT JOIN address a1 ON w.sender_address_id = a1.address_id "
            + "LEFT JOIN address a2 ON w.receiver_address_id = a2.address_id "
            + "LEFT JOIN package p ON w.package_id = p.package_id "
            + "LEFT JOIN channel c ON w.channel_id = c.channel_id "
            + "WHERE w.create_time BETWEEN #{startTime} AND #{endTime} "
            + "And w.user_Id = #{userId}"
            + "</script>")
    List<WaybillBo> selectWaybillBosByCreateTimeAndUserId(@Param("userId") Integer userId,
                                                           @Param("startTime") Timestamp startTime,
                                                           @Param("endTime") Timestamp endTime,
                                                           @Param("language") Integer language);
    @Select("<script>"
            + "SELECT "
            + "w.waybill_id AS waybillId, "
            + "w.user_id AS userId, "
            + "w.sender_address_id AS senderAddressId, "
            + "w.receiver_address_id AS receiverAddressId, "
            + "w.package_id AS packageId, "
            + "w.create_time AS createTime, "
            + "w.channel_id AS channelId, "
            + "w.status, "
            + "w.store_id AS storeId, "
            + "w.logistics_type AS logisticsType, "
            + "w.created_time AS createdTime, "
            + "w.paid_time AS paidTime, "
            + "w.sent_to_hub_time AS sentToHubTime, "
            + "w.shipped_from_hub_time AS shippedFromHubTime, "
            + "w.arrived_customs_time AS arrivedCustomsTime, "
            + "w.delivery_time AS deliveryTime, "
            + "w.delivery_confirmation_time AS deliveryConfirmationTime, "
            + "a1.address_id AS senderAddress.addressId, "
            + "CASE WHEN #{language} = 1 THEN a1.chinese_name ELSE a1.english_name END AS senderAddress.name, "
            + "a2.address_id AS receiverAddress.addressId, "
            + "CASE WHEN #{language} = 1 THEN a2.chinese_name ELSE a2.english_name END AS receiverAddress.name, "
            + "p.package_id AS packageBo.packageId, "
            + "c.channel_id AS channel.channelId, "
            + "CASE WHEN #{language} = 1 THEN c.chinese_name ELSE c.english_name END AS channel.name, "
            + "st.store_id AS storeId, "
            + "CASE WHEN #{language} = 1 THEN st.chinese_name ELSE st.english_name END AS storeName "
            + "FROM waybill w "
            + "LEFT JOIN address a1 ON w.sender_address_id = a1.address_id "
            + "LEFT JOIN address a2 ON w.receiver_address_id = a2.address_id "
            + "LEFT JOIN package p ON w.package_id = p.package_id "
            + "LEFT JOIN channel c ON w.channel_id = c.channel_id "
            + "LEFT JOIN store st ON w.store_id = st.store_id "
            + "WHERE w.user_id = #{userId} "
            + "</script>")
    List<WaybillBo> selectWaybillBosByUserId(@Param("userId") Integer userId, @Param("language") Integer language);
    @Select("<script>"
            + "SELECT "
            + "w.waybill_id AS waybillId, "
            + "w.user_id AS userId, "
            + "w.sender_address_id AS senderAddressId, "
            + "w.receiver_address_id AS receiverAddressId, "
            + "w.package_id AS packageId, "
            + "w.create_time AS createTime, "
            + "w.channel_id AS channelId, "
            + "w.status, "
            + "w.store_id AS storeId, "
            + "w.logistics_type AS logisticsType, "
            + "w.created_time AS createdTime, "
            + "w.paid_time AS paidTime, "
            + "w.sent_to_hub_time AS sentToHubTime, "
            + "w.shipped_from_hub_time AS shippedFromHubTime, "
            + "w.arrived_customs_time AS arrivedCustomsTime, "
            + "w.delivery_time AS deliveryTime, "
            + "w.delivery_confirmation_time AS deliveryConfirmationTime, "
            + "a1.address_id AS senderAddress.addressId, "
            + "CASE WHEN #{language} = 1 THEN a1.chinese_name ELSE a1.english_name END AS senderAddress.name, "
            + "a2.address_id AS receiverAddress.addressId, "
            + "CASE WHEN #{language} = 1 THEN a2.chinese_name ELSE a2.english_name END AS receiverAddress.name, "
            + "p.package_id AS packageBo.packageId, "
            + "c.channel_id AS channel.channelId, "
            + "CASE WHEN #{language} = 1 THEN c.chinese_name ELSE c.english_name END AS channel.name, "
            + "st.store_id AS storeId, "
            + "CASE WHEN #{language} = 1 THEN st.chinese_name ELSE st.english_name END AS storeName "
            + "FROM waybill w "
            + "LEFT JOIN address a1 ON w.sender_address_id = a1.address_id "
            + "LEFT JOIN address a2 ON w.receiver_address_id = a2.address_id "
            + "LEFT JOIN package p ON w.package_id = p.package_id "
            + "LEFT JOIN channel c ON w.channel_id = c.channel_id "
            + "LEFT JOIN store st ON w.store_id = st.store_id "
            + "WHERE w.user_id = #{userId} "
            + "AND w.status = #{status} "
            + "</script>")
    List<WaybillBo> selectWaybillBosByUserIdAndStatus(@Param("userId") Integer userId,@Param("status") Byte status, @Param("language") Integer language);
    @Select("<script>"
            + "SELECT "
            + "w.waybill_id AS waybillId, "
            + "w.user_id AS userId, "
            + "w.sender_address_id AS senderAddressId, "
            + "w.receiver_address_id AS receiverAddressId, "
            + "w.package_id AS packageId, "
            + "w.create_time AS createTime, "
            + "w.channel_id AS channelId, "
            + "w.status, "
            + "w.store_id AS storeId, "
            + "w.logistics_type AS logisticsType, "
            + "w.created_time AS createdTime, "
            + "w.paid_time AS paidTime, "
            + "w.sent_to_hub_time AS sentToHubTime, "
            + "w.shipped_from_hub_time AS shippedFromHubTime, "
            + "w.arrived_customs_time AS arrivedCustomsTime, "
            + "w.delivery_time AS deliveryTime, "
            + "w.delivery_confirmation_time AS deliveryConfirmationTime, "
            + "a1.address_id AS senderAddress.addressId, "
            + "CASE WHEN #{language} = 1 THEN a1.chinese_name ELSE a1.english_name END AS senderAddress.name, "
            + "a2.address_id AS receiverAddress.addressId, "
            + "CASE WHEN #{language} = 1 THEN a2.chinese_name ELSE a2.english_name END AS receiverAddress.name, "
            + "p.package_id AS packageBo.packageId, "
            + "c.channel_id AS channel.channelId, "
            + "CASE WHEN #{language} = 1 THEN c.chinese_name ELSE c.english_name END AS channel.name, "
            + "st.store_id AS storeId, "
            + "CASE WHEN #{language} = 1 THEN st.chinese_name ELSE st.english_name END AS storeName "
            + "FROM waybill w "
            + "LEFT JOIN address a1 ON w.sender_address_id = a1.address_id "
            + "LEFT JOIN address a2 ON w.receiver_address_id = a2.address_id "
            + "LEFT JOIN package p ON w.package_id = p.package_id "
            + "LEFT JOIN channel c ON w.channel_id = c.channel_id "
            + "LEFT JOIN store st ON w.store_id = st.store_id "+
            "WHERE " +
            "  w.store_id = #{storeId} AND " +
            "  (a2.chinese_name LIKE CONCAT('%', #{receiverName}, '%') OR " +
            "   a2.english_name LIKE CONCAT('%', #{receiverName}, '%')) " +
            "</script>")
    List<WaybillBo> selectWaybillBosByStoreIdAndReceiverName(@Param("storeId") Integer storeId,@Param("receiverName") String receiverName, @Param("language") Integer language);
    @Select("<script>"
            + "SELECT "
            + "w.waybill_id AS waybillId, "
            + "w.user_id AS userId, "
            + "w.sender_address_id AS senderAddressId, "
            + "w.receiver_address_id AS receiverAddressId, "
            + "w.package_id AS packageId, "
            + "w.create_time AS createTime, "
            + "w.channel_id AS channelId, "
            + "w.status, "
            + "w.store_id AS storeId, "
            + "w.logistics_type AS logisticsType, "
            + "w.created_time AS createdTime, "
            + "w.paid_time AS paidTime, "
            + "w.sent_to_hub_time AS sentToHubTime, "
            + "w.shipped_from_hub_time AS shippedFromHubTime, "
            + "w.arrived_customs_time AS arrivedCustomsTime, "
            + "w.delivery_time AS deliveryTime, "
            + "w.delivery_confirmation_time AS deliveryConfirmationTime, "
            + "a1.address_id AS senderAddress.addressId, "
            + "CASE WHEN #{language} = 1 THEN a1.chinese_name ELSE a1.english_name END AS senderAddress.name, "
            + "a2.address_id AS receiverAddress.addressId, "
            + "CASE WHEN #{language} = 1 THEN a2.chinese_name ELSE a2.english_name END AS receiverAddress.name, "
            + "p.package_id AS packageBo.packageId, "
            + "c.channel_id AS channel.channelId, "
            + "CASE WHEN #{language} = 1 THEN c.chinese_name ELSE c.english_name END AS channel.name, "
            + "st.store_id AS storeId, "
            + "CASE WHEN #{language} = 1 THEN st.chinese_name ELSE st.english_name END AS storeName "
            + "FROM waybill w "
            + "LEFT JOIN address a1 ON w.sender_address_id = a1.address_id "
            + "LEFT JOIN address a2 ON w.receiver_address_id = a2.address_id "
            + "LEFT JOIN package p ON w.package_id = p.package_id "
            + "LEFT JOIN channel c ON w.channel_id = c.channel_id "
            + "LEFT JOIN store st ON w.store_id = st.store_id "+
            "WHERE " +
            "  w.store_id = #{storeId} AND " +
            "  (a1.chinese_name LIKE CONCAT('%', #{senderName}, '%') OR " +
            "   a1.english_name LIKE CONCAT('%', #{senderName}, '%')) " +
            "</script>")
    List<WaybillBo> selectWaybillBosByStoreIdAndSenderName(@Param("storeId") Integer storeId,@Param("senderName") String senderName, @Param("language") Integer language);
    @Select("<script>"
            + "SELECT "
            + "w.waybill_id AS waybillId, "
            + "w.user_id AS userId, "
            + "w.sender_address_id AS senderAddressId, "
            + "w.receiver_address_id AS receiverAddressId, "
            + "w.package_id AS packageId, "
            + "w.create_time AS createTime, "
            + "w.channel_id AS channelId, "
            + "w.status, "
            + "w.store_id AS storeId, "
            + "w.logistics_type AS logisticsType, "
            + "w.created_time AS createdTime, "
            + "w.paid_time AS paidTime, "
            + "w.sent_to_hub_time AS sentToHubTime, "
            + "w.shipped_from_hub_time AS shippedFromHubTime, "
            + "w.arrived_customs_time AS arrivedCustomsTime, "
            + "w.delivery_time AS deliveryTime, "
            + "w.delivery_confirmation_time AS deliveryConfirmationTime, "
            + "a1.address_id AS senderAddress.addressId, "
            + "CASE WHEN #{language} = 1 THEN a1.chinese_name ELSE a1.english_name END AS senderAddress.name, "
            + "a2.address_id AS receiverAddress.addressId, "
            + "CASE WHEN #{language} = 1 THEN a2.chinese_name ELSE a2.english_name END AS receiverAddress.name, "
            + "p.package_id AS packageBo.packageId, "
            + "c.channel_id AS channel.channelId, "
            + "CASE WHEN #{language} = 1 THEN c.chinese_name ELSE c.english_name END AS channel.name, "
            + "st.store_id AS storeId, "
            + "CASE WHEN #{language} = 1 THEN st.chinese_name ELSE st.english_name END AS storeName "
            + "FROM waybill w "
            + "LEFT JOIN address a1 ON w.sender_address_id = a1.address_id "
            + "LEFT JOIN address a2 ON w.receiver_address_id = a2.address_id "
            + "LEFT JOIN package p ON w.package_id = p.package_id "
            + "LEFT JOIN channel c ON w.channel_id = c.channel_id "
            + "LEFT JOIN store st ON w.store_id = st.store_id "
            + "WHERE w.store_id = #{storeId} "
            + "AND (a1.phone = #{phone} OR a2.phone = #{phone}) "
            + "</script>")
    List<WaybillBo> selectWaybillBosByPhone(@Param("phone") String phone,@Param("storeId") Integer storeId, @Param("language") Integer language);
    @Select("<script>"
            + "SELECT "
            + "w.waybill_id AS waybillId, "
            + "w.user_id AS userId, "
            + "w.sender_address_id AS senderAddressId, "
            + "w.receiver_address_id AS receiverAddressId, "
            + "w.package_id AS packageId, "
            + "w.create_time AS createTime, "
            + "w.channel_id AS channelId, "
            + "w.status, "
            + "w.store_id AS storeId, "
            + "w.logistics_type AS logisticsType, "
            + "w.created_time AS createdTime, "
            + "w.paid_time AS paidTime, "
            + "w.sent_to_hub_time AS sentToHubTime, "
            + "w.shipped_from_hub_time AS shippedFromHubTime, "
            + "w.arrived_customs_time AS arrivedCustomsTime, "
            + "w.delivery_time AS deliveryTime, "
            + "w.delivery_confirmation_time AS deliveryConfirmationTime, "
            + "a1.address_id AS senderAddress.addressId, "
            + "CASE WHEN #{language} = 1 THEN a1.chinese_name ELSE a1.english_name END AS senderAddress.name, "
            + "a2.address_id AS receiverAddress.addressId, "
            + "CASE WHEN #{language} = 1 THEN a2.chinese_name ELSE a2.english_name END AS receiverAddress.name, "
            + "p.package_id AS packageBo.packageId, "
            + "c.channel_id AS channel.channelId, "
            + "CASE WHEN #{language} = 1 THEN c.chinese_name ELSE c.english_name END AS channel.name, "
            + "st.store_id AS storeId, "
            + "CASE WHEN #{language} = 1 THEN st.chinese_name ELSE st.english_name END AS storeName "
            + "FROM waybill w "
            + "INNER JOIN master_waybill_waybill mww ON w.waybill_id = mww.waybill_id"
            + "LEFT JOIN address a1 ON w.sender_address_id = a1.address_id "
            + "LEFT JOIN address a2 ON w.receiver_address_id = a2.address_id "
            + "LEFT JOIN package p ON w.package_id = p.package_id "
            + "LEFT JOIN channel c ON w.channel_id = c.channel_id "
            + "LEFT JOIN store st ON w.store_id = st.store_id "
            + "WHERE w.store_id = #{storeId} "
            + "AND mww.master_waybill_id = #{masterWaybillId}"
            + "</script>")
    List<WaybillBo> selectWaybillBosByMasterWaybillId(@Param("masterWaybillId") Integer masterWaybillId);



}